### ISSUE TITLE
Changing the Audit status of Optionset fields removes default value

### ISSUE THREAD

**Issue by altmank** [MscrmTools/MscrmTools.AuditCenter#2]
Hello, we've noticed that when we use the Audit Center on Optionset fields, the default optionset value is reset to nothing. This happens when the field is set in either direction, audited or not.

CRM On-Prem 8.2

**Comment by aruiz58** [comment]
Hi there, I am having the same problem.
A couple of fields in Contact entity and Opportunity Entity the default values got reset to nothing.
Now this is giving us errors.
Also, The Email relationship got broken for the TO and FROM fields, no values are coming in for FROM and the TO field is getting defaulted to the record owner/user.

CRM On-Prem 8.1.1.1005

**Comment by altmank** [comment]
@aruiz58 This has been open over a year with no response, so I wouldn't expect a fix on this.

**Comment by aruiz58** [comment]
And it also messed up our emails.Microsoft has not been able to find the issue and our emails are not good.We have a back up from before this happened but I do not know how to restore only metadata and keep our business data.


    On Monday, September 30, 2019, 03:14:12 PM MDT, altmank <notifications@github.com> wrote:  
 
 
@aruiz58 This has been open over a year with no response, so I wouldn't expect a fix on this.

**Comment by aruiz58** [comment]
Hi altmank,
Were you able to fix your issue?If so, how did you fix it?
    On Monday, September 30, 2019, 03:14:12 PM MDT, altmank <notifications@github.com> wrote:  
 
 
@aruiz58 This has been open over a year with no response, so I wouldn't expect a fix on this.

**Comment by MscrmTools** [comment]
Ok, sorry for the silence guys, I will look at this issue

**Comment by altmank** [comment]
@MscrmTools Thank you for resolving this!
