### ISSUE TITLE
NullReferenceException when loading entities

### ISSUE THREAD

**Issue by gregowens** [MscrmTools/MscrmTools.AuditCenter#3]
Not much to go on I'm afraid, but on loading entities I get an unhandled NRE:
![image](https://user-images.githubusercontent.com/2728236/52493278-f4124a80-2bc2-11e9-990d-03b0e45a49df.png)

---------------------------
Error
---------------------------
System.NullReferenceException: Object reference not set to an instance of an object.

   at MsCrmTools.AuditCenter.MainControl.<LoadEntities>b__15_1(RunWorkerCompletedEventArgs e)
---------------------------
OK   
---------------------------

**Comment by MscrmTools** [comment]
What is the CRM version?

**Comment by gregowens** [comment]
Dynamics 365 Online v9.1.0.1836

**Comment by MscrmTools** [comment]
I will need to test on my side on this version to see if it is related

**Comment by gregowens** [comment]
No problem - if I can enable any logging etc that might be helpful then do let me know 👍

**Comment by MscrmTools** [comment]
If you have access to an org on 9.0 or less and you can test the behavior, that would be great

**Comment by MscrmTools** [comment]
Well, I did the same access on a 9.1 of my own and I got no issue.
I will review the code to find the possible NullReferenceException

**Comment by MscrmTools** [comment]
Ok, the point might be that one of the entity or attribute that is activated for audit does not have a localized label for the currently connected user.

**Comment by gregowens** [comment]
Glad you were able to confirm it's not _all_ v9.1 deployments. FWIW I've just again checked on my TEST/PROD deployments and they work fine (I should have checked this before, sorry). However they originate entirely from the unmanaged DEV instance where this issue occurs. 

I'll review entities for missing labels shortly and report back.

**Comment by gregowens** [comment]
Thanks for the pointer Tanguy - it's fair to say that this looks to be a fringe case... I couldn't find missing labels using MetaData Browser or indeed the UI so I made a local build of Audit Center and added some extra trapping:
![image](https://user-images.githubusercontent.com/2728236/52556998-1506b580-2de6-11e9-84b9-3a5b840de1d3.png)

The result was unexpected - apparently I have an N:N relationship which is enabled for Audit! I really don't know how this is even possible so without writing code, I don't know how I'll disable the setting.

I guess a small patch to AuditCenter wouldn't hurt but otherwise I can rely on my local build until I "fix" my metadata.

**Comment by MscrmTools** [comment]
I will add a fix toi avoid this situation, thx
